"""
Code Generator Agent
Generates MCP server code from API specifications
"""

from typing import Any, Dict, Optional
from app.agents.base_agent import BaseAgent
from app.services.provider_service import ProviderService


class CodeGeneratorAgent(BaseAgent):
    """
    Agent that generates MCP server code from API specifications
    Uses AI provider to generate Python MCP server code
    """
    
    def __init__(self):
        """Initialize the code generator agent"""
        super().__init__(name="CodeGeneratorAgent")
        self.provider_service = ProviderService()
    
    async def execute(self, api_spec: Dict[str, Any]) -> str:
        """
        Generate MCP server code from API specification
        
        Args:
            api_spec: Dictionary containing API specification details
                     Expected keys: name, description, endpoints, etc.
        
        Returns:
            Generated Python MCP server code as a string
        """
        self.log_info("Starting code generation", spec_name=api_spec.get("name", "unknown"))
        
        try:
            # Try to get a provider
            provider = await self.provider_service.get_provider()
            
            if provider is None:
                # No provider available, return mock code
                self.log_warning("No provider available, returning mock code")
                return self._generate_mock_code(api_spec)
            
            # Generate prompt for the AI provider
            prompt = self._create_generation_prompt(api_spec)
            
            # Generate code using the provider
            self.log_info("Generating code with provider", provider_type=type(provider).__name__)
            generated_code = await provider.generate(prompt)
            
            self.log_info("Code generation completed successfully")
            return generated_code
            
        except Exception as e:
            self.log_error("Error during code generation", error=str(e))
            # Return mock code on error
            return self._generate_mock_code(api_spec)
    
    def _create_generation_prompt(self, api_spec: Dict[str, Any]) -> str:
        """
        Create a prompt for the AI provider to generate MCP server code
        
        Args:
            api_spec: API specification dictionary
            
        Returns:
            Formatted prompt string
        """
        name = api_spec.get("name", "MyAPI")
        description = api_spec.get("description", "API Server")
        endpoints = api_spec.get("endpoints", [])
        
        prompt = f"""Generate a Python MCP (Model Context Protocol) server for the following API:

API Name: {name}
Description: {description}

Endpoints:
"""
        
        for endpoint in endpoints:
            method = endpoint.get("method", "GET")
            path = endpoint.get("path", "/")
            desc = endpoint.get("description", "")
            prompt += f"- {method} {path}: {desc}\n"
        
        prompt += """
Requirements:
1. Use the MCP Python SDK
2. Implement all endpoints as MCP tools
3. Include proper error handling
4. Add docstrings and comments
5. Make it production-ready

Generate complete, working Python code for the MCP server.
"""
        
        return prompt
    
    def _generate_mock_code(self, api_spec: Dict[str, Any]) -> str:
        """
        Generate mock MCP server code when no provider is available
        
        Args:
            api_spec: API specification dictionary
            
        Returns:
            Mock Python MCP server code
        """
        name = api_spec.get("name", "MyAPI")
        description = api_spec.get("description", "API Server")
        
        mock_code = f'''"""
{name} MCP Server
{description}

This is a mock MCP server generated by AutoMCP.
Replace this with actual implementation.
"""

from mcp.server import Server
from mcp.types import Tool, TextContent
import asyncio


# Initialize MCP server
server = Server("{name.lower().replace(" ", "_")}")


@server.list_tools()
async def list_tools() -> list[Tool]:
    """List available tools"""
    return [
        Tool(
            name="example_tool",
            description="Example tool - replace with actual implementation",
            inputSchema={{
                "type": "object",
                "properties": {{
                    "input": {{
                        "type": "string",
                        "description": "Input parameter"
                    }}
                }},
                "required": ["input"]
            }}
        )
    ]


@server.call_tool()
async def call_tool(name: str, arguments: dict) -> list[TextContent]:
    """Handle tool calls"""
    if name == "example_tool":
        input_value = arguments.get("input", "")
        result = f"Processed: {{input_value}}"
        return [TextContent(type="text", text=result)]
    
    raise ValueError(f"Unknown tool: {{name}}")


async def main():
    """Run the MCP server"""
    from mcp.server.stdio import stdio_server
    
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            server.create_initialization_options()
        )


if __name__ == "__main__":
    asyncio.run(main())


# Generated by AutoMCP
# This is mock code - implement actual functionality
'''
        
        return mock_code


# Made with Bob